from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, model_validator

from app.pricing import format_price_benchmark


def utc_now() -> datetime:
    return datetime.now(timezone.utc)


class Evidence(BaseModel):
    source: str
    title: str
    text: str
    url: str = ""
    published_at: Optional[str] = None
    score: float = 0.0
    metadata: Dict[str, Any] = Field(default_factory=dict)


class ProblemSignal(BaseModel):
    problem: str
    customer_language: List[str] = Field(default_factory=list)
    # Legacy `frequency` is retained for stored-report compatibility. New scans
    # populate the explicit counts below; None means an older report did not save it.
    frequency: int = 1
    sentence_mentions: Optional[int] = None
    evidence_items: Optional[int] = None
    unique_contributors: Optional[int] = None
    evidence_urls: List[str] = Field(default_factory=list)
    urgency: float = Field(default=0.0, description="Internal heuristic input, not an observed measure of customer urgency.")
    objection_bucket: str = "Complexity/Confusion Friction"


class Opportunity(BaseModel):
    name: str
    audience: str
    promise: str
    format: List[str]
    problem_fit: float
    willingness_to_pay: float = Field(description="Legacy field name; current scans store a capped payment-language proxy, not measured willingness to pay.")
    competition_gap: float
    competition_gap_status: str = "not_assessed"
    evidence_strength: float
    validation_score: float
    pricing: Dict[str, str]
    pricing_rationale: str = ""
    value_hook: str = ""
    objection_bucket: str = "Complexity/Confusion Friction"
    components: List[str]
    differentiation: List[str]
    risks: List[str]
    next_steps: List[str]


class MarketplaceGap(BaseModel):
    marketplace: str
    title: str
    url: str = ""
    price: Optional[str] = Field(default=None, description="Observed listing price; None means it was not found in scraped text.")
    price_benchmark: Optional[str] = Field(default=None, description="Heuristic format-based estimate, never an observed marketplace price.")
    format: str = "Unknown"
    rating: str = "Not found"
    review_insights: List[str] = Field(default_factory=list)
    gap_signal: str = "Requires validation"

    @model_validator(mode="before")
    @classmethod
    def separate_legacy_estimates(cls, values):
        """Move price ranges generated by older collectors out of observed price."""
        if not isinstance(values, dict):
            return values
        values = dict(values)
        price = str(values.get("price") or "").strip()
        if price.lower() == "not found" or not price:
            values["price"] = None
            if price.lower() == "not found" and not values.get("price_benchmark"):
                values["price_benchmark"] = format_price_benchmark(values.get("format", ""))
        elif price in {"$19 – $29", "$29 – $49"}:
            values["price"] = None
            if not values.get("price_benchmark"):
                values["price_benchmark"] = price
        return values


class Report(BaseModel):
    id: str
    topic: str
    user_id: str = ""
    created_at: datetime = Field(default_factory=utc_now)
    scoring_version: str = "legacy"
    evidence: List[Evidence] = Field(default_factory=list)
    problems: List[ProblemSignal] = Field(default_factory=list)
    opportunities: List[Opportunity] = Field(default_factory=list)
    objection_matrix: Dict[str, List[str]] = Field(default_factory=dict)
    sales_hooks: List[str] = Field(default_factory=list)
    marketplace_gaps: List[MarketplaceGap] = Field(default_factory=list)
    gap_analysis: Dict[str, Any] = Field(default_factory=dict)
    product_blueprint: Dict[str, Any] = Field(default_factory=dict)
    launch_kit: Dict[str, Any] = Field(default_factory=dict)
    executive_summary: str = ""
    collection_notes: List[str] = Field(default_factory=list)
